window.gwtResources = {

 "examples_control": {
  "DropDownData_7": "Strawberries",
  "Title": "Title:",
  "DropDownData_6": "",
  "Control_Example": "Control Example",
  "DropDownData_5": "Kiwi",
  "DropDownData_4": "Peaches",
  "DropDownData_3": "Grapefruit",
  "DropDownData_2": "",
  "DropDownData_1": "Oranges",
  "DropDownData_0": "Apples",
  "FillDamage": "Fill Damaged Area With Color",
  "No_Parent": "No Parent",
  "Listeners": "Listeners",
  "Custom_Labels": "Custom Labels",
  "Background_Color": "Background Color",
  "Node_3_1": "Node 3.1",
  "MenuItem_SelectAll": "Select &All\tCtrl+A",
  "TabItem1_2": "Tab &2",
  "Node_1_1": "Node 1.1",
  "TabItem1_1": "Tab &1",
  "TabItem1_0": "Tab &0",
  "FileDialog": "FileDialog",
  "Image_Buttons": "Image Buttons",
  "Item_Background_Color": "Item 0 Background Color",
  "Use_Previous_Result": "Use Previous Result",
  "Preferred": "Preferred",
  "TableLine2_3": "yesterday",
  "Close_All_Shells": "Close All Shells",
  "TableLine2_2": "91571",
  "Info_long": "4",
  "TableLine2_1": "images",
  "PopupMenuHere": "Popup Menu Here",
  "TableLine2_0": "<empty>",
  "Foreground_Color": "Foreground Color",
  "TableLine0_3": "today",
  "2Radio": "Radio2",
  "TableLine0_2": "0",
  "TableLine0_1": "classes",
  "TableLine0_0": "<empty>",
  "Item_Styles": "Item Styles",
  "Set_Max_Visible": "Maximize",
  "Info_TabItem": "Tab 0",
  "Digits": "Digits",
  "Default": "Default (Inherit)",
  "Center": "Center",
  "Decoration_Styles": "Decoration Styles",
  "Images": "Images",
  "Item_Foreground_Color": "Item 0 Foreground Color",
  "ListData0_8": "Longest Line In List",
  "ListData0_7": "Line 8",
  "ListData0_6": "Line 7",
  "ListData0_5": "Line 6",
  "Resizable_Columns": "Resizable Columns",
  "ListData0_4": "Line 5",
  "Underline": "Underline",
  "Info_Rectangle": "0,0,20,10",
  "ListData0_3": "Line 4",
  "Item_Font": "Item 0 Font",
  "Push": "Push",
  "ListData0_2": "Line 3",
  "ListData0_1": "Line 2",
  "ListData0_0": "Line 1",
  "Radio": "Radio",
  "Node_4": "Node 4",
  "Node_3": "Node 3",
  "Node_2": "Node 2",
  "Header_Visible": "Header Visible",
  "Thumb": "Thumb",
  "Node_1": "Node 1",
  "Enabled": "Enabled",
  "No_Icon": "No Icon",
  "Info_TabItemA": "Tab 0,Tab 2",
  "Info_booleanA": "true,true,false",
  "File_Dialog_Styles": "FileDialog Styles",
  "Show_In_Tray": "Show In Tray",
  "CTabItem1_2": "CTabItem &2 has a long name",
  "CTabItem1_1": "CTabItem &1",
  "CTabItem1_0": "CTabItem &0",
  "1RadioWithMnemonic": "Radio&1",
  "FontDialog": "FontDialog",
  "Menu_Styles": "Menu Styles",
  "Background_Style": "Background",
  "Cell_Font": "Item 0 Col 1 Font",
  "MenuItem_Paste": "&Paste\tCtrl+V",
  "Info_TreeItem": "Node 1",
  "Info_boolean": "true",
  "Down": "Down",
  "Top_Right_Styles": "Top Right Styles",
  "BackgroundColor": "Background Color",
  "Two": "Two",
  "Parent": "Parent",
  "Dialog_Type": "Dialog Type",
  "Moveable_Columns": "Moveable Columns",
  "Wrap_Text": "Jack and Jill went up the hill to fetch a pail of water, Jack fell down and broke his crown and Jill came tumbling after!",
  "Set_Image": "Set Image",
  "Drop_Down": "Drop Down",
  "Info_TableItem": "Index:2",
  "2RadioWithMnemonic": "Radio&2",
  "Foreground_Style": "Foreground",
  "Listen": "Listen",
  "Italic": "Italic",
  "Show_Tooltip": "Tooltip",
  "Combo_child": "Combo Child",
  "Info_int": "4",
  "Three": "Three",
  "Colors": "Colors and Font",
  "DirectoryDialog": "DirectoryDialog",
  "Size": "Size",
  "CascadeWithMnemonic": "C&ascade",
  "CTabItem_content": "CTabItem Content",
  "Set_Single_Tabs": "Single Tab",
  "FilterName_3": "All Files (*)",
  "Change": "&Change...",
  "FilterName_2": "Doc Files (*.doc, *.rtf)",
  "MenuItem_Styles": "MenuItem Styles",
  "OK": "OK",
  "FilterName_1": "Batch Files (*.bat)",
  "CheckWithMnemonic": "&Check",
  "Edit_Event": "Edit Event",
  "Select_Listeners": "Select Listeners",
  "FilterName_0": "Text Files (*.txt)",
  "custom.window.title": "SWT Custom Controls",
  "Parameters": "Parameters",
  "Styles": "Styles",
  "Text_Labels": "Text Labels",
  "Node_2_2_1": "Node 2.2.1",
  "Modal_Styles": "Modal Styles",
  "Close": "Close",
  "Set_Get": "Set/Get API",
  "FullScreen": "Full Screen",
  "StyledText_Style_Instructions": "Select text, then style.",
  "Other": "Other",
  "LinkText": "Visit the <A HREF=\"www.eclipse.org\">Eclipse.org</A> project and the <A HREF=\"www.eclipse.org\swt\">SWT</A> homepage.",
  "Background_Mode": "Background Mode on Parent",
  "Orientation": "Orientation",
  "Font": "Font",
  "window.title": "SWT Controls",
  "MessageBox": "MessageBox",
  "One_Two_Three": "One Two Three",
  "BackgroundImage": "Background Image",
  "Info_StringA": "hello,there",
  "Tree_With_Images": "Tree With Images",
  "Right": "Right",
  "Text_ToolBar": "Text ToolBar",
  "Selection": "Selection",
  "Selection_Foreground_Color": "Selection Foreground Color",
  "WebKitNotFound": "Cannot use SWT.WEBKIT style:  {0}\nSee http://www.eclipse.org/swt/faq.php#howusewebkit for more information.",
  "Left": "Left",
  "Info_TableItemA": "Index:2,Index:4",
  "Cell_Background_Color": "Item 0 Col 1 Background Color",
  "Selection_Background_Color": "Selection Background Color",
  "Increment": "Increment",
  "SubSubMenu": "Sub-Sub-Menu",
  "TableTree_column": "Column",
  "MozillaNotFound": "Cannot use SWT.MOZILLA style:  {0}\nSee http://www.eclipse.org/swt/faq.php#howusemozilla for more information.",
  "Page_Increment": "Page Increment",
  "Accelerators": "Accelerators",
  "Dialog_Result": "Dialog Result",
  "PopupMenu": "Popup Menu",
  "Cell_Foreground_Color": "Item 0 Col 1 Foreground Color",
  "Button_Styles": "MessageBox Button Styles",
  "Node_2_2": "Node 2.2",
  "Text_Direction": "Text Direction",
  "Node_2_1": "Node 2.1",
  "error.CouldNotLoadResources": "Unable to load resources",
  "Info_intA": "0,1,2",
  "Item1_Text": "What is your favorite button?",
  "Visible": "Visible",
  "Info_Point": "0,0",
  "Select_All": "Select All",
  "Sort_Indicator": "Sort Indicator",
  "Info_charA": "a,b,c",
  "One": "One",
  "TableLine1_3": "tomorrow",
  "TableLine1_2": "2556",
  "TableLine1_1": "databases",
  "TableLine1_0": "<empty>",
  "Deselect_All": "Deselect All",
  "ListData1_8": "The Longest String",
  "ListData1_7": "Strawberries",
  "Example_string": "The quick brown fox jumps over the lazy dog.",
  "ListData1_6": "Apricots",
  "ListData1_5": "Kiwi",
  "ListData1_4": "Peaches",
  "ListData1_3": "Grapefruit",
  "ListData1_2": "Bananas",
  "ListData1_1": "Oranges",
  "Multi_line": "A multi line text widget.",
  "Header_Images": "Header Images",
  "ListData1_0": "Apples",
  "Returning": "<- Returning: ",
  "CItem_Colors": "CTabItem Colors",
  "Custom_Combo": "Custom Combo",
  "MenuItem_Cut": "Cu&t\tCtrl+X",
  "TableTitle_3": "Modified",
  "TableTitle_2": "Size",
  "Image_ToolBar": "Image ToolBar",
  "TableTitle_1": "Type",
  "TableTitle_0": "Name",
  "TabItem_content": "TabItem Content",
  "Set_Min_Visible": "Minimize",
  "Cascade": "Cascade",
  "SubMenu": "Sub-Menu",
  "StyledText_Styles": "Text Styles",
  "Info_char": "c",
  "BrowserNotFound": "Browser not found:  {0}",
  "Mnemonics": "Mnemonics",
  "Defaults": "&Defaults",
  "Set_Unselected_Image_Visible": "Image on Unselected Tabs",
  "Bold": "Bold",
  "Minimum": "Minimum",
  "Set_Simple_Tabs": "Simple Tabs",
  "Locked": "Locked",
  "Info_String": "hello",
  "Up": "Up",
  "Set_Unselected_Close_Visible": "Close on Unselected Tabs",
  "Parameter_Info": "{0}   e.g. {1} ",
  "ToolTip_Title": "Foxes vs. Dogs",
  "Text_Buttons": "Text Buttons",
  "Alignment": "Alignment",
  "Item2_Text": "What is your favorite icon?",
  "Create_Dialog": "Create Dialog",
  "Pack_Columns": "Pack Columns",
  "RadioWithMnemonic": "&Radio",
  "Image_Text_Buttons": "Image and Text Buttons",
  "Index": "Index:",
  "Info_longA": "0,1,2",
  "Images_failed": "Warning: Failed to load images",
  "UntypedEvents": "Untyped Events",
  "1Radio": "Radio1",
  "Create_Shell": "Create Shell",
  "Button": "Button",
  "ColorDialog": "ColorDialog",
  "ImageText_ToolBar": "Image and Text ToolBar",
  "Image_Labels": "Image Labels",
  "Strikeout": "Strikeout",
  "Multiple_Columns": "Multiple Columns",
  "PrintDialog": "PrintDialog",
  "Info_TreeItemA": "Node 1,Node 3",
  "Maximum": "Maximum",
  "Sub_Images": "Sub Images",
  "Check": "Check",
  "Result": "Result: {0}",
  "Clear": "Clear",
  "Tooltip": "Tooltip:  {0}",
  "Lines_Visible": "Lines Visible",
  "Set_Top_Right": "Set Top Right",
  "ColorTitle_3": "Color",
  "ColorTitle_2": "RGB",
  "ColorTitle_1": "Type",
  "MenuItem_Copy": "&Copy\tCtrl+C",
  "ColorTitle_0": "Name",
  "Title_Text": "Title Text",
  "Fill_Y": "Vertical Fill",
  "Fill_X": "Horizontal Fill",
  "Icon_Styles": "MessageBox Icon Styles",
  "Edit_Event_Fields": "On {0}, return the following:",
  "PushWithMnemonic": "&Push",
  "DropDownData_8": "The Longest String"
 }
};
